modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="NonKungCh"
description="Dynamic color mixing for Minecraft 1.21+ Created by NonKungCh."

[[dependencies.colormix]]
modId="neoforge"
type="required"
version="${neo_version}"
ordering="NONE"
side="BOTH"

[[dependencies.colormix]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
